config/routes.rb
GeneralApp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users
  match 'user_confirmation' => 'users#user_confirmation', :as => :confirmation
  match '/update_password' => 'users#update_password'
  match '/destroy' => 'sessions#destroy'

  resources :sessions

  resources :homes
  get '/terms' => 'homes#terms', :as => :terms
  get '/privacy' => 'homes#privacy', :as => :privacy
  get '/category' => 'homes#category', :as => :category
  get '/sub_category/:id' => 'homes#sub_category', :as => :subcategory
  get '/item/:id' => 'homes#item', :as => :item
  get '/item_record/:id' => 'homes#item_record', :as => :item_record

  resources :contacts
  post '/contact' => 'contacts#contact'

  resources :forgot_password
  match '/forgot_password/edit/:password_reset_token' => 'forgot_password#edit', :as => :Change_password

    root :to => 'users#index'

end

app/controllers/forgot_password_controller.rb
class ForgotPasswordController < ApplicationController
	
   skip_before_filter :authorize

	def create
			@user = User.find_by_email(params[:email])
			@user.send_password_reset if @user
			render :json => {
				            :responseCode => "200",
	                        :responseMessage => "Email sent with password reset instructions."							
						  	}
	end

	def edit
			@user = User.find_by_password_reset_token(params[:password_reset_token])
			if @user.nil?
				render :text => {		      	
		           				:responseMessage => "You password reset token is expired. Please try again"							
							    }
    	end							   
	end

	def update
	    	@user = User.find_by_password_reset_token(params[:user][:password_reset_token])
	     if @user.password_reset_sent_at > Time.zone.now + 2.hours
	    	@user.password_reset_token = nil
    		   render :json => {
							  	:responseCode => "400",
	                         	:responseMessage => "You password reset token is expired. Please try again"					
							   }
	  elsif @user.update_attributes(:password => Digest::SHA1.hexdigest(params[:user][:password]))
			@user.password_reset_token = nil
			@user.password_reset_created_at = Time.now.utc
			@user.save
			   render :json => {
							     :responseCode => "200",
	                             :responseMessage => "Password has been reset successfully"							
							    }
	   else
	           render :json => {
							    :responseCode => "0",
	                            :responseMessage => "cant change"		
		                        }
	    end
	end		
end				

app/helpers/forgot_password_helper.rb
module ForgotPasswordHelper
end

app/views/forgot_password/edit.html.erb
<%= form_for @user, :url => forgot_password_path(params[:password_reset_token]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.hidden_field :password_reset_token %>
   </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>

  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div> 
  <div class="actions"><%= f.submit "Update Password" %></div>
         <%#= f.submit 'Clear Form', :type => 'reset' %>
<% end %>